### ISSUE TITLE
Failed to run bootstrapper for plugins/SimpleJumpPads-1.2.2.jar. This plugin will not be loaded.

### ISSUE THREAD

**Issue by GreenedDev** [4drian3d/SimpleJumpPads#16]
Here is error: https://paste.md-5.net/sopiyuhiwe.pl
Details:
Java 17
Paper 1.19.4

**Comment by 4drian3d** [comment]
> Here is error: https://paste.md-5.net/sopiyuhiwe.pl Details: Java 17 Paper 1.19.4

Try with Paper 1.19.4, Paper 1.20.1 or Purpur 1.20.1. I have seen that Purpur 1.19.4 has problems with several Paper-only plugins
