### ISSUE TITLE
Supporting WorldGuard

### ISSUE THREAD

**Issue by highright1234** [4drian3d/SimpleJumpPads#8]
I think WorldGuard blocks using jumppad
I know allowing use flag will work
Do you have any plans to allow to use jumppad on WorldGuard region?
Probably setting a priority could work

**Comment by 4drian3d** [comment]
This is a WorldGuard flags issue, you can modify your region flags to allow interaction with pressure plates and with https://github.com/LuckPerms/ExtraContexts together with LuckPerms limit the `simplejumppads.jump` permission (which is required to use any jumppad) in certain regions. I don't think a special plugin integration is required just for this
